### ISSUE TITLE
404 after reload

### ISSUE THREAD

**Issue by ivozandhuis** [netwerk-digitaal-erfgoed/LDWizard-Core#9]
Reloading http://localhost:8080/1 results in a 404. On ldwizard.netwerkdigitaalerfgoed.nl this is resolved somehow. Could this be resolved in the Core?

**Comment by wouterbeek** [comment]
The [GeoDataWizard](https://labs.kadaster.nl/demonstrators/geodatawizard/) also has this issue (also returns a 404 after browser refresh).

Maybe people that deploy the browser need some guidance on how to deploy (since this was fixed somehow for the NDE deployment).

**Comment by GerwinBosch** [comment]
Should be fixed by https://github.com/netwerk-digitaal-erfgoed/LDWizard-Core/commit/e8075b0935a82a7561ecdc57c78016fba1b5f6d4

**Comment by GerwinBosch** [comment]
@ivozandhuis this should be fixed by replacing the current router with a hash-router (e.g. `/1` becomes /#1). Please re-open if  this does not solve the issue (version is already live in  [netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard](https://github.com/netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard))
